#!/bin/sh

#
# UTILITY FUNCTIONS
#

c () { bspc config "$@" & }
R () { bspc rule -a "$@" & }
s () { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# Set wallpaper
feh --bg-scale ~/Wallpapers/the_wallpaper.jpg

# bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

R Gimp desktop=^8 follow=on floating=on
R Chromium desktop=^3
R mplayer2 floating=on
R Kupfer.py focus=on
R Screenkey manage=off
R zoom state=floating center=on follow=on border=off desktop="^10"
R Emacs state=tiled follow=on desktop="^1"
R Alacritty state=tiled follow=on desktop="^2"
R firefox state=tiled follow=on desktop="^3"
R Neomutt state=tiled follow=on desktop="^4"
R Slicer follow=off desktop="^9"
R Thunar state=floating


C border_width 2
C window_gap 12

C split_ratio 0.52
C borderless_monocle true
C gapless_monocle true

termAppRatio=0.75
screenwidth=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3}')
screenheight=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
windowwidth=$( echo "${screenwidth} * ${termAppRatio} "| bc)
windowheight=$( echo "${screenheight} * ${termAppRatio}" | bc)
windowx=$( echo "${screenwidth}/2.0 - ${windowwidth}/2.0"| bc)
windowy=$( echo "${screenheight}/2.0 - ${windowheight}/2.0" | bc)

R TermApp state=floating rectangle=${windowwidth%%.*}x${windowheight%%.*}+$windowx+$windowy

# Launch Polybar
${HOME}/.config/polybar/launch.sh --docky

# Launch bluetooth widget
blueberry-tray

# Launch dropbox
dropbox&
